name: Update README

on:
  push:
    branches:
      - main
    paths:
      - "[0-9]*. */**"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Check changed files
        run: |
          echo "Changed files in this push:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^[0-9]+\.' || echo "No matching changes"

      - name: Update README
        if: ${{ success() && contains(github.event.head_commit.message, 'solve:') }}
        run: |
          echo "Updating README for new solution..."
          python update_readme.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --staged --quiet || (git commit -m "docs: update README.md" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
